using System.Diagnostics;
using System.Drawing.Imaging;
using System.Runtime.InteropServices;

namespace BrPatchHub;

public sealed class MainForm : Form
{
    private enum LibraryState { NotFound, Available, Installed, UpdateAvailable, VerificationRequired }
    private enum UiIcon { Library, CheckCircle, Download, Warning, Question, MissingFolder, Steam, Folder, Package, Calendar, Shield, Verify, Trash, Restore }
    private static readonly Color Bg = Color.FromArgb(13, 36, 61), Panel = Color.FromArgb(18, 50, 82), Panel2 = Color.FromArgb(25, 65, 105), Border = Color.FromArgb(58, 94, 132), TextMain = Color.FromArgb(240, 245, 255), TextMuted = Color.FromArgb(198, 213, 232), Blue = Color.FromArgb(47, 118, 255), Green = Color.FromArgb(68, 221, 106), Yellow = Color.FromArgb(255, 203, 35), Red = Color.FromArgb(255, 88, 88), Gray = Color.FromArgb(174, 190, 211);
    private readonly Storage _storage; private readonly OnlineServices _online; private readonly TranslationService _translations; private readonly CancellationTokenSource _closing = new();
    private Catalog _catalog = new(); private Translation? _selected;
    private readonly Dictionary<string, string> _foundPaths = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, LibraryState> _states = new(StringComparer.OrdinalIgnoreCase);
    private readonly HashSet<string> _verificationRequired = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, Image> _covers = new(StringComparer.OrdinalIgnoreCase);
    private readonly TextBox _search = new(); private readonly ComboBox _filter = new(); private readonly FlowLayoutPanel _games = new(); private readonly Label _libraryCount = new(); private readonly Label _lastCheck = new(); private readonly Label _generalStatus = new(); private readonly ProgressBar _appUpdateBar = new(); private readonly Label _appUpdatePercent = new(); private readonly Panel _detailHost = new(); private readonly RichTextBox _log = new(); private readonly Panel _logHost = new(); private readonly Button _logToggle = new();
    private readonly Label _summaryCatalog = new(), _summaryInstalled = new(), _summaryUpdates = new(), _summaryAvailable = new(), _summaryMissing = new();
    private readonly Label _legendInstalled = new(), _legendAvailable = new(), _legendUpdates = new(), _legendMissing = new();
    private Image? _brandImage; private Image? _personalLogo; private Image? _iconSheet; private Image? _statusIconSheet; private SplitContainer? _bodySplit; private TableLayoutPanel? _detailRoot; private Panel? _operationPanel; private ProgressBar? _operationBar; private Label? _operationTitle; private Label? _operationDetail; private Label? _operationPercent; private bool _busy; private bool _searchHint;
    private sealed record QueueChoice(Translation Translation, string Path) { public override string ToString() => $"{Translation.Game} | pt-BR | v{Translation.Version}"; }

    private sealed class IconView : Control
    {
        private readonly UiIcon _kind; private readonly Color _accent; private readonly Image? _image; private readonly Rectangle? _sourceRectangle;
        public IconView(UiIcon kind, Color accent, Image? image = null, Rectangle? sourceRectangle = null) { _kind = kind; _accent = accent; _image = image; _sourceRectangle = sourceRectangle; Size = new Size(28, 28); MinimumSize = new Size(28, 28); Margin = new Padding(0); BackColor = Panel; SetStyle(ControlStyles.UserPaint | ControlStyles.AllPaintingInWmPaint | ControlStyles.OptimizedDoubleBuffer, true); }
        protected override void OnPaintBackground(PaintEventArgs e) { using var brush = new SolidBrush(Parent?.BackColor ?? Panel); e.Graphics.FillRectangle(brush, ClientRectangle); }
        protected override void OnPaint(PaintEventArgs e)
        {
            base.OnPaint(e); e.Graphics.SmoothingMode = System.Drawing.Drawing2D.SmoothingMode.AntiAlias; var w = Math.Max(16, ClientSize.Width); var h = Math.Max(16, ClientSize.Height); var cx = w / 2f; var cy = h / 2f; using var pen = new Pen(_accent, Math.Max(1.7f, w / 14f)) { StartCap = System.Drawing.Drawing2D.LineCap.Round, EndCap = System.Drawing.Drawing2D.LineCap.Round, LineJoin = System.Drawing.Drawing2D.LineJoin.Round }; using var brush = new SolidBrush(_accent); var r = Math.Min(w, h) * .32f; if (_image is not null) { var side = Math.Min(w, h) * .86f; var destination = new RectangleF(cx - side / 2, cy - side / 2, side, side); if (_sourceRectangle is Rectangle source) e.Graphics.DrawImage(_image, destination, new RectangleF(source.X, source.Y, source.Width, source.Height), GraphicsUnit.Pixel); else e.Graphics.DrawImage(_image, destination); return; }
            switch (_kind)
            {
                case UiIcon.Library: e.Graphics.DrawRectangle(pen, cx - r * .9f, cy - r * .55f, r * 1.8f, r * 1.25f); e.Graphics.DrawLine(pen, cx - r * .9f, cy - r * .55f, cx - r * .55f, cy - r * .9f); e.Graphics.DrawLine(pen, cx - r * .55f, cy - r * .9f, cx + r * .9f, cy - r * .9f); break;
                case UiIcon.CheckCircle: e.Graphics.DrawEllipse(pen, cx - r, cy - r, r * 2, r * 2); e.Graphics.DrawLines(pen, [new PointF(cx - r * .48f, cy), new PointF(cx - r * .1f, cy + r * .42f), new PointF(cx + r * .62f, cy - r * .42f)]); break;
                case UiIcon.Download: e.Graphics.DrawLine(pen, cx, cy - r * .95f, cx, cy + r * .35f); e.Graphics.DrawLines(pen, [new PointF(cx - r * .45f, cy - r * .05f), new PointF(cx, cy + r * .45f), new PointF(cx + r * .45f, cy - r * .05f)]); e.Graphics.DrawLine(pen, cx - r * .8f, cy + r * .85f, cx + r * .8f, cy + r * .85f); break;
                case UiIcon.Warning: e.Graphics.DrawPolygon(pen, [new PointF(cx, cy - r), new PointF(cx + r * .9f, cy + r * .78f), new PointF(cx - r * .9f, cy + r * .78f)]); e.Graphics.DrawLine(pen, cx, cy - r * .38f, cx, cy + r * .25f); e.Graphics.FillEllipse(brush, cx - 1.3f, cy + r * .48f, 2.6f, 2.6f); break;
                case UiIcon.Question: e.Graphics.DrawEllipse(pen, cx - r, cy - r, r * 2, r * 2); using (var f = new Font("Segoe UI", Math.Max(10, r * 1.65f), FontStyle.Bold)) using (var sf = new StringFormat { Alignment = StringAlignment.Center, LineAlignment = StringAlignment.Center }) e.Graphics.DrawString("?", f, brush, new RectangleF(cx - r, cy - r, r * 2, r * 2), sf); break;
                case UiIcon.MissingFolder:
                    using (var folderBrush = new SolidBrush(Color.FromArgb(244, 190, 55))) using (var folderPen = new Pen(Color.FromArgb(255, 221, 112), Math.Max(1.4f, w / 18f)) { LineJoin = System.Drawing.Drawing2D.LineJoin.Round })
                    {
                        var folder = new System.Drawing.Drawing2D.GraphicsPath(); folder.AddPolygon([new PointF(cx - r, cy - r * .48f), new PointF(cx - r * .32f, cy - r * .48f), new PointF(cx - r * .06f, cy - r * .8f), new PointF(cx + r * .92f, cy - r * .8f), new PointF(cx + r, cy + r * .72f), new PointF(cx - r, cy + r * .72f)]); e.Graphics.FillPath(folderBrush, folder); e.Graphics.DrawPath(folderPen, folder);
                    }
                    using (var badgeBrush = new SolidBrush(Color.FromArgb(92, 105, 120))) using (var badgePen = new Pen(Color.FromArgb(225, 232, 240), Math.Max(1.5f, w / 18f)) { StartCap = System.Drawing.Drawing2D.LineCap.Round, EndCap = System.Drawing.Drawing2D.LineCap.Round })
                    { var bx = cx + r * .56f; var by = cy + r * .46f; var br = r * .48f; e.Graphics.FillEllipse(badgeBrush, bx - br, by - br, br * 2, br * 2); e.Graphics.DrawLine(badgePen, bx - br * .38f, by - br * .38f, bx + br * .38f, by + br * .38f); e.Graphics.DrawLine(badgePen, bx + br * .38f, by - br * .38f, bx - br * .38f, by + br * .38f); }
                    break;
                case UiIcon.Steam: e.Graphics.DrawEllipse(pen, cx - r, cy - r, r * 2, r * 2); e.Graphics.DrawEllipse(pen, cx - r * .3f, cy - r * .3f, r * .6f, r * .6f); e.Graphics.DrawLine(pen, cx - r * .65f, cy + r * .48f, cx - r * .12f, cy + r * .1f); e.Graphics.DrawLine(pen, cx - r * .12f, cy + r * .1f, cx + r * .28f, cy - r * .12f); break;
                case UiIcon.Folder: e.Graphics.DrawLines(pen, [new PointF(cx - r, cy - r * .35f), new PointF(cx - r * .35f, cy - r * .35f), new PointF(cx - r * .1f, cy - r * .72f), new PointF(cx + r, cy - r * .72f), new PointF(cx + r * .85f, cy + r * .7f), new PointF(cx - r, cy + r * .7f), new PointF(cx - r, cy - r * .35f)]); break;
                case UiIcon.Package: e.Graphics.DrawRectangle(pen, cx - r * .78f, cy - r * .62f, r * 1.56f, r * 1.35f); e.Graphics.DrawLine(pen, cx - r * .78f, cy - r * .62f, cx, cy - r * .1f); e.Graphics.DrawLine(pen, cx + r * .78f, cy - r * .62f, cx, cy - r * .1f); e.Graphics.DrawLine(pen, cx, cy - r * .1f, cx, cy + r * .72f); break;
                case UiIcon.Calendar: e.Graphics.DrawRectangle(pen, cx - r, cy - r * .65f, r * 2, r * 1.45f); e.Graphics.DrawLine(pen, cx - r, cy - r * .15f, cx + r, cy - r * .15f); e.Graphics.DrawLine(pen, cx - r * .48f, cy - r * .92f, cx - r * .48f, cy - r * .42f); e.Graphics.DrawLine(pen, cx + r * .48f, cy - r * .92f, cx + r * .48f, cy - r * .42f); break;
                case UiIcon.Shield: e.Graphics.DrawPolygon(pen, [new PointF(cx, cy - r), new PointF(cx + r * .82f, cy - r * .55f), new PointF(cx + r * .68f, cy + r * .52f), new PointF(cx, cy + r), new PointF(cx - r * .68f, cy + r * .52f), new PointF(cx - r * .82f, cy - r * .55f)]); e.Graphics.DrawLines(pen, [new PointF(cx - r * .38f, cy), new PointF(cx - r * .08f, cy + r * .3f), new PointF(cx + r * .45f, cy - r * .3f)]); break;
                case UiIcon.Verify: e.Graphics.DrawEllipse(pen, cx - r, cy - r, r * 2, r * 2); e.Graphics.DrawLines(pen, [new PointF(cx - r * .42f, cy), new PointF(cx - r * .08f, cy + r * .34f), new PointF(cx + r * .55f, cy - r * .35f)]); break;
                case UiIcon.Trash: e.Graphics.DrawRectangle(pen, cx - r * .6f, cy - r * .55f, r * 1.2f, r * 1.35f); e.Graphics.DrawLine(pen, cx - r * .82f, cy - r * .78f, cx + r * .82f, cy - r * .78f); e.Graphics.DrawLine(pen, cx - r * .32f, cy - r, cx + r * .32f, cy - r); e.Graphics.DrawLine(pen, cx - r * .2f, cy - r * .25f, cx - r * .2f, cy + r * .52f); e.Graphics.DrawLine(pen, cx + r * .2f, cy - r * .25f, cx + r * .2f, cy + r * .52f); break;
                case UiIcon.Restore: e.Graphics.DrawArc(pen, cx - r, cy - r, r * 2, r * 2, 42, 285); e.Graphics.DrawLines(pen, [new PointF(cx - r * .94f, cy - r * .05f), new PointF(cx - r * .94f, cy - r * .62f), new PointF(cx - r * .38f, cy - r * .62f)]); break;
            }
        }
    }

    private sealed class CoverView : PictureBox
    {
        public bool FitEntireImage { get; init; }
        public bool UniformFrame { get; init; }
        public CoverView() { DoubleBuffered = true; BackColor = Panel; SizeMode = PictureBoxSizeMode.Normal; }
        protected override void OnPaint(PaintEventArgs e)
        {
            e.Graphics.Clear(BackColor); if (Image is null) return; e.Graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.HighQualityBicubic; e.Graphics.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.HighQuality;
            var source = ContentBounds(Image); if (UniformFrame) { const float frameAspect = 460f / 215f; var width = (float)ClientSize.Width; var height = width / frameAspect; if (height > ClientSize.Height) { height = ClientSize.Height; width = height * frameAspect; } var frame = new RectangleF((ClientSize.Width - width) / 2f, (ClientSize.Height - height) / 2f, width, height); e.Graphics.DrawImage(Image, frame, source, GraphicsUnit.Pixel); return; } var scale = FitEntireImage ? Math.Min(ClientSize.Width / (float)source.Width, ClientSize.Height / (float)source.Height) : Math.Max(ClientSize.Width / (float)source.Width, ClientSize.Height / (float)source.Height); var drawnWidth = source.Width * scale; var drawnHeight = source.Height * scale; var destination = new RectangleF((ClientSize.Width - drawnWidth) / 2f, (ClientSize.Height - drawnHeight) / 2f, drawnWidth, drawnHeight); e.Graphics.DrawImage(Image, destination, source, GraphicsUnit.Pixel);
        }
        private static Rectangle ContentBounds(Image image)
        {
            if (image is not Bitmap bitmap || bitmap.Width < 20 || bitmap.Height < 20) return new Rectangle(0, 0, image.Width, image.Height); var left = 0; var top = 0; var right = bitmap.Width - 1; var bottom = bitmap.Height - 1; var maxX = bitmap.Width / 4; var maxY = bitmap.Height / 4;
            while (top < maxY && IsDarkRow(bitmap, top)) top++; while (bottom > bitmap.Height - 1 - maxY && IsDarkRow(bitmap, bottom)) bottom--; while (left < maxX && IsDarkColumn(bitmap, left, top, bottom)) left++; while (right > bitmap.Width - 1 - maxX && IsDarkColumn(bitmap, right, top, bottom)) right--;
            return right - left > 10 && bottom - top > 10 ? Rectangle.FromLTRB(left, top, right + 1, bottom + 1) : new Rectangle(0, 0, bitmap.Width, bitmap.Height);
        }
        private static bool IsDarkRow(Bitmap bitmap, int y) { var dark = 0; var samples = 0; for (var x = 0; x < bitmap.Width; x += 2) { var color = bitmap.GetPixel(x, y); if (color.A < 20 || Math.Max(color.R, Math.Max(color.G, color.B)) <= 12) dark++; samples++; } return dark >= samples * .96; }
        private static bool IsDarkColumn(Bitmap bitmap, int x, int top, int bottom) { var dark = 0; var samples = 0; for (var y = top; y <= bottom; y += 2) { var color = bitmap.GetPixel(x, y); if (color.A < 20 || Math.Max(color.R, Math.Max(color.G, color.B)) <= 12) dark++; samples++; } return dark >= samples * .96; }
    }

    public MainForm(Storage? storage = null, bool initializeOnline = true) { _storage = storage ?? new Storage(); _online = new OnlineServices(_storage); _translations = new TranslationService(_storage, Log); LoadBrandImage(); LoadWindowIcon(); LoadIconSheet(); BuildUi(); WireEvents(initializeOnline); if (!initializeOnline) LoadPreviewData(); }
    private void LoadPreviewData() { var bundled = Path.Combine(AppContext.BaseDirectory, "catalog.json"); _catalog = _storage.Read<Catalog>(bundled) ?? new Catalog(); EnsureStates(); RefreshGameList(); var first = _catalog.Translations.FirstOrDefault(); if (first is not null) SelectTranslation(first); }
    private void LoadBrandImage() { using var stream = typeof(MainForm).Assembly.GetManifestResourceStream("BrPatchHub.logo.png"); if (stream is not null) { using var source = Image.FromStream(stream); _brandImage = new Bitmap(source); } using var personalStream = typeof(MainForm).Assembly.GetManifestResourceStream("BrPatchHub.gabriel-logo.png"); if (personalStream is not null) { using var personalSource = Image.FromStream(personalStream); _personalLogo = new Bitmap(personalSource); } }
    private void LoadWindowIcon() { using var stream = typeof(MainForm).Assembly.GetManifestResourceStream("BrPatchHub.app.ico"); if (stream is null) return; using var source = new Icon(stream); Icon = (Icon)source.Clone(); }
    private void LoadIconSheet() { using var stream = typeof(MainForm).Assembly.GetManifestResourceStream("BrPatchHub.ui-icons.png"); if (stream is not null) { using var source = Image.FromStream(stream); _iconSheet = new Bitmap(source); } using var statusStream = typeof(MainForm).Assembly.GetManifestResourceStream("BrPatchHub.status-icons.png"); if (statusStream is not null) { using var source = Image.FromStream(statusStream); using var original = new Bitmap(source); _statusIconSheet = RemoveDarkBackground(original); } }
    private static Bitmap RemoveDarkBackground(Bitmap source) { var result = new Bitmap(source.Width, source.Height, PixelFormat.Format32bppArgb); using (var graphics = Graphics.FromImage(result)) graphics.DrawImageUnscaled(source, 0, 0); var area = new Rectangle(0, 0, result.Width, result.Height); var data = result.LockBits(area, ImageLockMode.ReadWrite, PixelFormat.Format32bppArgb); try { var bytes = new byte[Math.Abs(data.Stride) * data.Height]; Marshal.Copy(data.Scan0, bytes, 0, bytes.Length); for (var y = 0; y < data.Height; y++) for (var x = 0; x < data.Width; x++) { var offset = y * data.Stride + x * 4; var maximum = Math.Max(bytes[offset], Math.Max(bytes[offset + 1], bytes[offset + 2])); bytes[offset + 3] = maximum <= 45 ? (byte)0 : maximum < 130 ? (byte)((maximum - 45) * 255 / 85) : (byte)255; } Marshal.Copy(bytes, 0, data.Scan0, bytes.Length); } finally { result.UnlockBits(data); } return result; }

    private void BuildUi()
    {
        Text = AppConstants.AppName; StartPosition = FormStartPosition.CenterScreen; MinimumSize = new Size(1280, 760); Size = new Size(1520, 940); BackColor = Bg; ForeColor = TextMain; Font = new Font("Segoe UI", 9.5f); AutoScaleMode = AutoScaleMode.Dpi;
        var root = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 1, RowCount = 3, Padding = new Padding(14, 10, 14, 6) }; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 88)); root.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); root.RowStyles.Add(new RowStyle(SizeType.Absolute, 64)); Controls.Add(root); root.Controls.Add(BuildHeader(), 0, 0);
        var body = new SplitContainer { Dock = DockStyle.Fill, SplitterWidth = 8, BackColor = Border }; _bodySplit = body; body.Panel1.BackColor = Bg; body.Panel2.BackColor = Bg; root.Controls.Add(body, 0, 1); body.Panel1.Controls.Add(BuildLibrary()); body.Panel2.Controls.Add(BuildDetailArea()); root.Controls.Add(BuildFooter(), 0, 2);
    }
    protected override void OnShown(EventArgs e) { base.OnShown(e); if (_bodySplit is not null && _bodySplit.Width > 1050) _bodySplit.SplitterDistance = 410; }
    private Control BuildHeader()
    {
        var h = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 4, RowCount = 2 }; h.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 420)); h.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); h.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 195)); h.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 255)); h.RowStyles.Add(new RowStyle(SizeType.Absolute, 51)); h.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
        var logos = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 2, RowCount = 1, Margin = new Padding(0, 0, 18, 2) }; logos.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80)); logos.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); var personalLogo = new PictureBox { Dock = DockStyle.Fill, Image = _personalLogo, SizeMode = PictureBoxSizeMode.Zoom, Margin = new Padding(0, 2, 8, 2), BackColor = Bg }; var centralLogo = new PictureBox { Dock = DockStyle.Fill, Image = _brandImage, SizeMode = PictureBoxSizeMode.Zoom, Margin = new Padding(0), BackColor = Bg }; logos.Controls.Add(personalLogo, 0, 0); logos.Controls.Add(centralLogo, 1, 0); h.Controls.Add(logos, 0, 0); h.SetRowSpan(logos, 2);
        var title = LabelOf("Traduções, correções e mods para seus jogos", 11, FontStyle.Bold, TextMain); title.TextAlign = ContentAlignment.BottomLeft; h.Controls.Add(title, 1, 0); var sub = LabelOf($"BR Patch Hub • v{AppConstants.AppVersion}", 9, FontStyle.Regular, TextMuted); sub.TextAlign = ContentAlignment.TopLeft; h.Controls.Add(sub, 1, 1);
        var tools = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 1, RowCount = 2, Margin = new Padding(0) }; tools.RowStyles.Add(new RowStyle(SizeType.Percent, 50)); tools.RowStyles.Add(new RowStyle(SizeType.Percent, 50)); var queue = ButtonOf("Fila de instalações", false); queue.Margin = new Padding(3, 1, 3, 1); queue.Click += async (_, _) => await ShowInstallQueueAsync(); tools.Controls.Add(queue, 0, 0); var scan = ButtonOf("Escanear biblioteca", false); scan.Margin = new Padding(3, 1, 3, 1); scan.Click += async (_, _) => await ScanLibraryAsync(true); tools.Controls.Add(scan, 0, 1); h.Controls.Add(tools, 2, 0); h.SetRowSpan(tools, 2); var settings = ButtonOf("Configurações", false); settings.Click += (_, _) => ShowSettings(); h.Controls.Add(settings, 3, 0);
        var credits = LabelOf("Créditos: Gabriel Michel e Fl4sh9174", 8.5f, FontStyle.Bold, Color.FromArgb(255, 211, 105)); credits.TextAlign = ContentAlignment.BottomRight; credits.AutoEllipsis = false; credits.AutoSize = false; credits.Dock = DockStyle.Fill; h.Controls.Add(credits, 3, 1); return h;
    }
    private Control BuildLibrary()
    {
        var host = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 1, RowCount = 5, Padding = new Padding(0, 10, 8, 0) }; host.RowStyles.Add(new RowStyle(SizeType.Absolute, 48)); host.RowStyles.Add(new RowStyle(SizeType.Absolute, 45)); host.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); host.RowStyles.Add(new RowStyle(SizeType.Absolute, 185)); host.RowStyles.Add(new RowStyle(SizeType.Absolute, 33));
        var sr = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 2, BackColor = Bg }; sr.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); sr.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 125)); _search.Text = "Buscar jogo..."; _searchHint = true; _search.Multiline = true; _search.AcceptsReturn = false; _search.Dock = DockStyle.Fill; _search.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right; _search.Margin = new Padding(0, 4, 8, 6); StyleInput(_search); _search.BorderStyle = BorderStyle.Fixed3D; _search.ForeColor = TextMuted; sr.Controls.Add(_search, 0, 0); _filter.Dock = DockStyle.Fill; _filter.Margin = new Padding(0, 4, 0, 6); _filter.DropDownStyle = ComboBoxStyle.DropDownList; _filter.Items.AddRange(["Todos", "Instalados", "Disponíveis", "Atualizações", "Não instalados"]); _filter.SelectedIndex = 0; StyleInput(_filter); sr.Controls.Add(_filter, 1, 0); host.Controls.Add(sr, 0, 0);
        var heading = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 2 }; heading.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); heading.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90)); heading.Controls.Add(LabelOf("BIBLIOTECA", 10, FontStyle.Bold, TextMain), 0, 0); _libraryCount.TextAlign = ContentAlignment.MiddleRight; _libraryCount.ForeColor = TextMuted; heading.Controls.Add(_libraryCount, 1, 0); host.Controls.Add(heading, 0, 1);
        _games.Dock = DockStyle.Fill; _games.FlowDirection = FlowDirection.TopDown; _games.WrapContents = false; _games.AutoScroll = true; _games.BackColor = Bg; _games.Padding = new Padding(0, 0, 3, 0); host.Controls.Add(_games, 0, 2); host.Controls.Add(BuildLegend(), 0, 3);
        _lastCheck.Text = "Última verificação: ainda não realizada    ↻"; _lastCheck.ForeColor = TextMuted; _lastCheck.Dock = DockStyle.Fill; _lastCheck.TextAlign = ContentAlignment.MiddleLeft; _lastCheck.Cursor = Cursors.Hand; _lastCheck.Click += async (_, _) => await RefreshCatalogAndScanAsync(); host.Controls.Add(_lastCheck, 0, 4); return host;
    }
    private Control BuildLegend()
    {
        var card = Card(); card.Padding = new Padding(14, 9, 14, 8); var table = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 1, RowCount = 5, BackColor = Panel }; table.RowStyles.Add(new RowStyle(SizeType.Absolute, 28)); for (var i = 1; i < 5; i++) table.RowStyles.Add(new RowStyle(SizeType.Percent, 25)); table.Controls.Add(LabelOf("LEGENDA DE STATUS", 9, FontStyle.Bold, TextMain), 0, 0); table.Controls.Add(LegendRow(UiIcon.CheckCircle, "Instalada", "Tradução instalada", Green, _legendInstalled, StatusCrop(1)), 0, 1); table.Controls.Add(LegendRow(UiIcon.Download, "Disponível", "Pronta para instalação", Color.FromArgb(58, 156, 255), _legendAvailable, StatusCrop(3)), 0, 2); table.Controls.Add(LegendRow(UiIcon.Warning, "Atualização disponível", "Nova versão no catálogo", Yellow, _legendUpdates, StatusCrop(2)), 0, 3); table.Controls.Add(LegendRow(UiIcon.MissingFolder, "Não instalado", "Jogo não encontrado", Gray, _legendMissing, StatusCrop(4)), 0, 4); card.Controls.Add(table); return card;
    }
    private Control LegendRow(UiIcon icon, string name, string desc, Color color, Label count, Rectangle crop) { var row = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 4 }; row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 34)); row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150)); row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 34)); var ico = new IconView(icon, color, icon == UiIcon.MissingFolder ? null : _statusIconSheet, crop) { Dock = DockStyle.Fill, Margin = new Padding(2) }; row.Controls.Add(ico, 0, 0); row.Controls.Add(LabelOf(name, 9, FontStyle.Bold, color), 1, 0); row.Controls.Add(LabelOf(desc, 8.5f, FontStyle.Regular, TextMuted), 2, 0); count.TextAlign = ContentAlignment.MiddleRight; count.ForeColor = color; count.Font = new Font("Segoe UI", 9, FontStyle.Bold); count.Dock = DockStyle.Fill; row.Controls.Add(count, 3, 0); return row; }
    private Control BuildDetailArea()
    {
        var outer = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, RowCount = 2, ColumnCount = 1, Padding = new Padding(8, 10, 0, 0) }; outer.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); outer.RowStyles.Add(new RowStyle(SizeType.Absolute, 0)); _detailHost.Dock = DockStyle.Fill; _detailHost.BackColor = Bg; _detailHost.AutoScroll = true; outer.Controls.Add(_detailHost, 0, 0); _logHost.Dock = DockStyle.Fill; _logHost.BackColor = Color.FromArgb(3, 13, 27); _logHost.Padding = new Padding(8); _log.Dock = DockStyle.Fill; _log.ReadOnly = true; _log.BackColor = _logHost.BackColor; _log.ForeColor = TextMuted; _log.Font = new Font("Consolas", 9); _log.BorderStyle = BorderStyle.None; _logHost.Controls.Add(_log); outer.Controls.Add(_logHost, 0, 1); _logToggle.Tag = outer; ShowWelcome(); return outer;
    }
    private Control BuildFooter()
    {
        var f = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 3, RowCount = 1, Margin = new Padding(0), Padding = new Padding(0, 4, 0, 2), MinimumSize = new Size(0, 58) }; f.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50)); f.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 150)); f.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50)); f.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
        var updateArea = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 2, RowCount = 2, Margin = new Padding(0) }; updateArea.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); updateArea.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 52)); updateArea.RowStyles.Add(new RowStyle(SizeType.Absolute, 26)); updateArea.RowStyles.Add(new RowStyle(SizeType.Absolute, 20)); _generalStatus.Text = "Preparando biblioteca..."; _generalStatus.ForeColor = Green; _generalStatus.TextAlign = ContentAlignment.MiddleLeft; updateArea.Controls.Add(_generalStatus, 0, 0); updateArea.SetColumnSpan(_generalStatus, 2); _appUpdateBar.Dock = DockStyle.Fill; _appUpdateBar.Margin = new Padding(0, 2, 8, 2); _appUpdateBar.Minimum = 0; _appUpdateBar.Maximum = 100; _appUpdateBar.Style = ProgressBarStyle.Continuous; _appUpdateBar.Visible = false; updateArea.Controls.Add(_appUpdateBar, 0, 1); _appUpdatePercent.Dock = DockStyle.Fill; _appUpdatePercent.TextAlign = ContentAlignment.MiddleRight; _appUpdatePercent.ForeColor = Yellow; _appUpdatePercent.Font = new Font("Segoe UI", 9, FontStyle.Bold); _appUpdatePercent.Visible = false; updateArea.Controls.Add(_appUpdatePercent, 1, 1); f.Controls.Add(updateArea, 0, 0);
        _logToggle.Text = "Ver log"; _logToggle.Dock = DockStyle.Fill; _logToggle.Margin = new Padding(0); _logToggle.FlatStyle = FlatStyle.Flat; _logToggle.FlatAppearance.BorderSize = 0; _logToggle.ForeColor = TextMuted; _logToggle.BackColor = Bg; _logToggle.TextAlign = ContentAlignment.MiddleCenter; _logToggle.Click += (_, _) => ToggleLog(); f.Controls.Add(_logToggle, 1, 0); var gh = new LinkLabel { Text = "Acompanhe no GitHub", Dock = DockStyle.Fill, AutoSize = false, Margin = new Padding(0), Padding = new Padding(0, 0, 2, 0), TextAlign = ContentAlignment.MiddleRight, LinkColor = TextMuted, BackColor = Bg }; gh.LinkClicked += (_, _) => OpenUrl(AppConstants.OfficialRepositoryUrl); f.Controls.Add(gh, 2, 0); return f;
    }

    private void WireEvents(bool online) { FormClosing += (_, _) => _closing.Cancel(); _search.GotFocus += (_, _) => { if (!_searchHint) return; _searchHint = false; _search.Text = ""; _search.ForeColor = TextMain; }; _search.LostFocus += (_, _) => { if (!string.IsNullOrWhiteSpace(_search.Text)) return; _searchHint = true; _search.Text = "Buscar jogo..."; _search.ForeColor = TextMuted; }; _search.TextChanged += (_, _) => { if (!_searchHint) RefreshGameList(); }; _filter.SelectedIndexChanged += (_, _) => RefreshGameList(); if (online) Shown += async (_, _) => await InitializeAsync(); }
    private async Task InitializeAsync() { var bundled = Path.Combine(AppContext.BaseDirectory, "catalog.json"); _catalog = _storage.LoadCatalogCache() ?? _storage.Read<Catalog>(bundled) ?? new Catalog(); EnsureStates(); RefreshGameList(); try { _catalog = await _online.RefreshCatalogAsync(_closing.Token); Log($"Catálogo atualizado com {_catalog.Translations.Count} traduções."); } catch (Exception ex) { Log($"Catálogo online indisponível; usando cópia local. {ex.Message}"); } EnsureStates(); await ScanLibraryAsync(false); await CheckAppUpdateAsync(); }

    private async Task CheckAppUpdateAsync()
    {
        AppVersionManifest? update;
        try { update = await _online.CheckAppUpdateAsync(_closing.Token); }
        catch (OperationCanceledException) { return; }
        if (update is null || IsDisposed) return;

        var notes = string.IsNullOrWhiteSpace(update.Notes) ? "" : $"\r\n\r\nNovidades:\r\n{update.Notes}";
        var answer = MessageBox.Show(this, $"Uma nova versão do BR Patch Hub está disponível.\r\n\r\nAtual: v{AppConstants.AppVersion}\r\nNova: v{update.Version}{notes}\r\n\r\nDeseja baixar e instalar agora?", "Atualização do BR Patch Hub", MessageBoxButtons.YesNo, MessageBoxIcon.Information);
        if (answer != DialogResult.Yes) return;

        var executable = Environment.ProcessPath;
        if (string.IsNullOrWhiteSpace(executable) || !executable.EndsWith(".exe", StringComparison.OrdinalIgnoreCase) || Path.GetFileName(executable).Equals("dotnet.exe", StringComparison.OrdinalIgnoreCase))
        {
            OnlineServices.OpenUpdate(update);
            return;
        }

        try
        {
            _generalStatus.ForeColor = Yellow;
            _appUpdateBar.Value = 0; _appUpdateBar.Visible = true; _appUpdatePercent.Text = "0%"; _appUpdatePercent.Visible = true;
            var progress = new Progress<ProgressInfo>(info => { _generalStatus.Text = info.Message; if (info.Percent.HasValue) { var percent = Math.Clamp(info.Percent.Value, 0, 100); _appUpdateBar.Style = ProgressBarStyle.Continuous; _appUpdateBar.Value = percent; _appUpdatePercent.Text = $"{percent}%"; } else { _appUpdateBar.Style = ProgressBarStyle.Marquee; _appUpdatePercent.Text = "..."; } });
            var downloaded = await _online.DownloadUpdateAsync(update, _storage.Root, progress, _closing.Token);
            _appUpdateBar.Style = ProgressBarStyle.Continuous; _appUpdateBar.Value = 100; _appUpdatePercent.Text = "100%"; _generalStatus.Text = "Atualização validada. Reiniciando...";
            UpdateInstaller.Start(downloaded, executable, update.Sha256);
            _closing.Cancel();
            Application.Exit();
        }
        catch (OperationCanceledException) { }
        catch (Exception ex)
        {
            Log($"Falha ao atualizar o BR Patch Hub: {ex.Message}");
            _generalStatus.Text = "Falha ao atualizar o BR Patch Hub";
            _generalStatus.ForeColor = Red;
            MessageBox.Show(this, $"Não foi possível instalar a atualização.\r\n\r\n{ex.Message}", "Falha na atualização", MessageBoxButtons.OK, MessageBoxIcon.Error);
        }
        finally { if (!_closing.IsCancellationRequested) { _appUpdateBar.Visible = false; _appUpdatePercent.Visible = false; } }
    }
    private void EnsureStates() { foreach (var item in _catalog.Translations) { if (_storage.Installed.TryGetValue(item.Id, out var installed) && _foundPaths.ContainsKey(item.Id) && Directory.Exists(installed.GamePath)) _states[item.Id] = _verificationRequired.Contains(item.Id) || !SemanticVersion.TryCompare(installed.Version, item.Version, out var comparison) ? LibraryState.VerificationRequired : comparison < 0 ? LibraryState.UpdateAvailable : LibraryState.Installed; else if (_foundPaths.ContainsKey(item.Id)) _states[item.Id] = LibraryState.Available; else _states[item.Id] = LibraryState.NotFound; } }
    private async Task ScanLibraryAsync(bool announce)
    {
        SetBusy(true); _generalStatus.Text = "Escaneando bibliotecas Steam..."; _generalStatus.ForeColor = Yellow; if (announce) Log("Escaneamento geral iniciado."); try { _foundPaths.Clear(); await Task.Run(() => { foreach (var item in _catalog.Translations) { var path = SteamService.FindGame(item); if (path is null && _storage.Config.GamePaths.TryGetValue(item.Id, out var manual) && IsValidGameFolder(item, manual)) path = manual; if (path is not null) _foundPaths[item.Id] = path; } }); ReconcileUninstalledGames(); await ReconcileInstallationHealthAsync(); EnsureStates(); _storage.Config.LastCatalogCheck = DateTimeOffset.Now; _storage.SaveConfig(); _lastCheck.Text = $"Última verificação: {DateTime.Now:dd/MM/yyyy HH:mm}"; var updates = _states.Values.Any(x => x == LibraryState.UpdateAvailable); _generalStatus.Text = updates ? "Há atualizações disponíveis" : "Tudo atualizado!"; _generalStatus.ForeColor = updates ? Yellow : Green; RefreshGameList(); if (_selected is not null) ShowDetails(_selected); if (announce) Log("Escaneamento concluído."); } finally { SetBusy(false); }
    }
    private void ReconcileUninstalledGames() { var changed = false; foreach (var item in _catalog.Translations) { if (!_storage.Installed.ContainsKey(item.Id) || _foundPaths.ContainsKey(item.Id)) continue; _storage.Installed.Remove(item.Id); _storage.Config.GamePaths.Remove(item.Id); Log($"Jogo desinstalado detectado; registro antigo removido: {item.Game}. Backups físicos preservados."); changed = true; } if (changed) { _storage.SaveInstalled(); _storage.SaveConfig(); } }
    private async Task ReconcileInstallationHealthAsync()
    {
        _verificationRequired.Clear();
        foreach (var item in _catalog.Translations.Where(x => _storage.Installed.ContainsKey(x.Id) && _foundPaths.ContainsKey(x.Id)).ToList())
        {
            _generalStatus.Text = $"Verificando instalação: {item.Game}";
            var health = await _translations.GetInstallationHealthAsync(item.Id, _closing.Token);
            if (health == InstallationHealth.OriginalRestored)
            {
                _storage.Installed.Remove(item.Id);
                Log($"Tradução já restaurada externamente; registro removido: {item.Game}. Backups físicos preservados.");
            }
            else if (health == InstallationHealth.Modified)
            {
                _verificationRequired.Add(item.Id);
                Log($"Verificação necessária: os arquivos de {item.Game} não correspondem à tradução registrada nem ao backup original.");
            }
        }
        _storage.SaveInstalled();
    }
    private async Task RefreshCatalogAndScanAsync() { try { _catalog = await _online.RefreshCatalogAsync(_closing.Token); Log("Catálogo atualizado manualmente."); } catch (Exception ex) { Log($"Falha ao atualizar catálogo: {ex.Message}"); _generalStatus.Text = "Não foi possível atualizar o catálogo"; _generalStatus.ForeColor = Red; } await ScanLibraryAsync(false); }
    private void RefreshGameList()
    {
        if (_games.IsDisposed) return; _games.SuspendLayout(); _games.Controls.Clear(); var query = _searchHint ? "" : _search.Text.Trim(); var filter = _filter.SelectedItem?.ToString() ?? "Todos"; var items = _catalog.Translations.Where(x => string.IsNullOrWhiteSpace(query) || x.Game.Contains(query, StringComparison.CurrentCultureIgnoreCase)).Where(x => FilterMatches(StateOf(x), filter)); foreach (var item in items.OrderBy(x => x.Game)) _games.Controls.Add(BuildGameCard(item)); _games.ResumeLayout(true); _libraryCount.Text = $"{_catalog.Translations.Count} jogos"; UpdateSummary();
    }
    private Control BuildGameCard(Translation item)
    {
        var state = StateOf(item); var selected = _selected?.Id == item.Id; var card = new Panel { Width = Math.Max(320, _games.ClientSize.Width - 25), Height = 101, Margin = new Padding(0, 0, 0, 7), BackColor = selected ? Color.FromArgb(13, 47, 79) : Panel, Cursor = Cursors.Hand, Padding = new Padding(8) }; card.Paint += (_, e) => { using var pen = new Pen(selected ? Blue : Border, selected ? 2 : 1); e.Graphics.DrawRectangle(pen, 0, 0, card.Width - 1, card.Height - 1); };
        var t = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = card.BackColor, ColumnCount = 3, RowCount = 3 }; t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 145)); t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 76)); t.RowStyles.Add(new RowStyle(SizeType.Percent, 45)); t.RowStyles.Add(new RowStyle(SizeType.Percent, 25)); t.RowStyles.Add(new RowStyle(SizeType.Percent, 30)); card.Controls.Add(t); var cover = new CoverView { Dock = DockStyle.Fill, FitEntireImage = true, UniformFrame = true, BackColor = card.BackColor, Image = _covers.GetValueOrDefault(item.Id) ?? _brandImage, Margin = new Padding(0, 0, 10, 0) }; t.Controls.Add(cover, 0, 0); t.SetRowSpan(cover, 3); _ = LoadCoverAsync(item, cover); var name = LabelOf(item.Game, 10, FontStyle.Bold, TextMain); t.Controls.Add(name, 1, 0); t.Controls.Add(LabelOf("Steam", 8.5f, FontStyle.Regular, TextMuted), 1, 1); t.Controls.Add(LabelOf(StateText(state), 8.5f, FontStyle.Bold, StateColor(state)), 1, 2); var version = LabelOf($"v{item.Version}", 9, FontStyle.Regular, TextMuted); version.TextAlign = ContentAlignment.TopRight; t.Controls.Add(version, 2, 0); WireCardClicks(card, item); return card;
    }
    private async Task LoadCoverAsync(Translation item, PictureBox target) { if (string.IsNullOrWhiteSpace(item.SteamAppId) || _covers.ContainsKey(item.Id)) return; try { using var client = new HttpClient { Timeout = TimeSpan.FromSeconds(5) }; var bytes = await client.GetByteArrayAsync($"https://cdn.cloudflare.steamstatic.com/steam/apps/{item.SteamAppId}/header.jpg", _closing.Token); using var stream = new MemoryStream(bytes); using var source = Image.FromStream(stream); var image = new Bitmap(source); _covers[item.Id] = image; if (!target.IsDisposed) target.Image = image; } catch { } }
    private void WireCardClicks(Control control, Translation item) { control.Click += (_, _) => SelectTranslation(item); foreach (Control child in control.Controls) WireCardClicks(child, item); }
    private void SelectTranslation(Translation item) { if (_busy) return; if (_selected?.Id == item.Id) { ShowDetails(item); return; } _selected = item; RefreshGameList(); ShowDetails(item); }
    private void ShowWelcome() { _detailHost.Controls.Clear(); var welcome = LabelOf("Selecione um jogo na biblioteca para gerenciar sua tradução.", 15, FontStyle.Bold, TextMuted); welcome.Dock = DockStyle.Fill; welcome.TextAlign = ContentAlignment.MiddleCenter; _detailHost.Controls.Add(welcome); }
    private void ShowDetails(Translation item)
    {
        _detailHost.SuspendLayout(); _detailHost.Controls.Clear(); _detailRoot = new TableLayoutPanel { Dock = DockStyle.Top, AutoSize = true, BackColor = Bg, ColumnCount = 1, RowCount = 7 }; _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 210)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 110)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 66)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 0)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 250)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 142)); _detailRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 8)); _detailRoot.Controls.Add(BuildHero(item), 0, 0); _detailRoot.Controls.Add(BuildFacts(item), 0, 1); _detailRoot.Controls.Add(BuildActions(item), 0, 2); _detailRoot.Controls.Add(BuildOperationPanel(), 0, 3); _detailRoot.Controls.Add(BuildInformation(item), 0, 4); _detailRoot.Controls.Add(BuildSummary(), 0, 5); _detailHost.Controls.Add(_detailRoot); _detailHost.ResumeLayout();
    }
    private Control BuildHero(Translation item)
    {
        var state = StateOf(item); var installedVersion = _storage.Installed.GetValueOrDefault(item.Id)?.Version; var versionText = state == LibraryState.UpdateAvailable ? $"Instalada: v{installedVersion}   •   Nova: v{item.Version}" : state == LibraryState.VerificationRequired ? $"Versão instalada desconhecida   •   Catálogo: v{item.Version}" : $"v{item.Version}"; var card = Card(); card.Margin = new Padding(0, 0, 0, 10); card.Padding = new Padding(18, 16, 18, 14); var t = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 3, RowCount = 4 }; t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 275)); t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 260)); t.RowStyles.Add(new RowStyle(SizeType.Absolute, 54)); t.RowStyles.Add(new RowStyle(SizeType.Absolute, 38)); t.RowStyles.Add(new RowStyle(SizeType.Absolute, 32)); t.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); card.Controls.Add(t); var cover = new CoverView { Dock = DockStyle.Fill, FitEntireImage = true, UniformFrame = true, Image = _covers.GetValueOrDefault(item.Id) ?? _brandImage, BackColor = Panel, Margin = new Padding(0, 4, 20, 4) }; t.Controls.Add(cover, 0, 0); t.SetRowSpan(cover, 4); _ = LoadCoverAsync(item, cover); t.Controls.Add(LabelOf(item.Game, 23, FontStyle.Bold, TextMain), 1, 0); t.Controls.Add(LabelOf("Tradução PT-BR", 13, FontStyle.Bold, TextMuted), 1, 1); t.Controls.Add(LabelOf($"{versionText}   •   {StateText(state).ToUpperInvariant()}", 8.5f, FontStyle.Bold, StateColor(state)), 1, 2); var authorGold = Color.FromArgb(255, 211, 105); var author = new LinkLabel { Text = "Tradução feita por Gabriel Michel", Dock = DockStyle.Fill, LinkColor = authorGold, ActiveLinkColor = Color.White, VisitedLinkColor = authorGold, BackColor = Panel, Font = new Font("Segoe UI", 9, FontStyle.Bold), TextAlign = ContentAlignment.TopLeft }; author.LinkClicked += (_, _) => OpenUrl(item.ReleaseUrl); t.Controls.Add(author, 1, 3); var status = BuildHeroStatus(item); t.Controls.Add(status, 2, 0); t.SetRowSpan(status, 4); return card;
    }
    private Control BuildHeroStatus(Translation item)
    {
        var state = StateOf(item);
        var box = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 2, RowCount = 3, Padding = new Padding(8, 12, 0, 4) };
        box.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 40)); box.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
        box.RowStyles.Add(new RowStyle(SizeType.Absolute, 48)); box.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); box.RowStyles.Add(new RowStyle(SizeType.Absolute, state == LibraryState.NotFound ? 42 : 0));
        var icon = state switch { LibraryState.Installed => UiIcon.CheckCircle, LibraryState.Available => UiIcon.Download, LibraryState.UpdateAvailable or LibraryState.VerificationRequired => UiIcon.Warning, _ => UiIcon.MissingFolder };
        box.Controls.Add(new IconView(icon, StateColor(state)) { Dock = DockStyle.Fill, Margin = new Padding(3) }, 0, 0);
        box.Controls.Add(LabelOf(StateText(state), 10, FontStyle.Bold, StateColor(state)), 1, 0);
        var compatibility = LabelOf(CompatibilityText(item, state), 9, FontStyle.Regular, TextMuted); compatibility.TextAlign = ContentAlignment.MiddleLeft; box.Controls.Add(compatibility, 1, 1);
        if (state == LibraryState.NotFound) { var locate = ButtonOf("Localizar jogo manualmente", false); locate.Margin = new Padding(0, 4, 0, 0); locate.Click += (_, _) => LocateGameManually(item); box.Controls.Add(locate, 1, 2); }
        return box;
    }
    private Control BuildOperationPanel() { _operationPanel = Card(); _operationPanel.Padding = new Padding(14, 8, 14, 8); var box = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 3, RowCount = 3 }; box.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 170)); box.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); box.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 54)); box.RowStyles.Add(new RowStyle(SizeType.Absolute, 22)); box.RowStyles.Add(new RowStyle(SizeType.Absolute, 20)); box.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); _operationTitle = LabelOf("Operação em andamento", 9, FontStyle.Bold, TextMain); box.Controls.Add(_operationTitle, 0, 0); box.SetColumnSpan(_operationTitle, 3); _operationDetail = LabelOf("Preparando...", 8.5f, FontStyle.Regular, TextMuted); _operationDetail.TextAlign = ContentAlignment.MiddleLeft; box.Controls.Add(_operationDetail, 0, 1); box.SetColumnSpan(_operationDetail, 3); _operationBar = new ProgressBar { Dock = DockStyle.Fill, Style = ProgressBarStyle.Continuous, Minimum = 0, Maximum = 100, Value = 0, Margin = new Padding(0, 3, 10, 3) }; box.Controls.Add(_operationBar, 0, 2); box.SetColumnSpan(_operationBar, 2); _operationPercent = LabelOf("0%", 9, FontStyle.Bold, Blue); _operationPercent.TextAlign = ContentAlignment.MiddleRight; box.Controls.Add(_operationPercent, 2, 2); _operationPanel.Controls.Add(box); _operationPanel.Visible = false; return _operationPanel; }
    private Control BuildFacts(Translation item)
    {
        var row = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 4, RowCount = 1, Padding = new Padding(0, 7, 0, 8) }; for (var i = 0; i < 4; i++) row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25)); row.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); var installed = _storage.Installed.GetValueOrDefault(item.Id); var path = _foundPaths.GetValueOrDefault(item.Id) ?? installed?.GamePath ?? "Não instalado"; var steam = FactCard(UiIcon.Steam, "Plataforma", "Steam", Color.White, _iconSheet, new Rectangle(205, 40, 485, 460)); WireClicks(steam, () => OpenSteamPage(item)); row.Controls.Add(steam, 0, 0); var location = FactCard(UiIcon.Folder, "Local do jogo", WrapPath(path), Color.White, _iconSheet, new Rectangle(830, 60, 500, 450)); location.Cursor = Cursors.Hand; WireClicks(location, () => { if (StateOf(item) == LibraryState.NotFound) LocateGameManually(item); else OpenFolder(path); }); SetToolTip(location, StateOf(item) == LibraryState.NotFound ? "Clique para localizar o jogo manualmente." : path); row.Controls.Add(location, 1, 0); var installedText = installed is null ? "—" : string.IsNullOrWhiteSpace(installed.Version) ? "Desconhecida" : StateOf(item) == LibraryState.UpdateAvailable ? $"v{installed.Version}\r\nNova: v{item.Version}" : $"v{installed.Version}"; row.Controls.Add(FactCard(UiIcon.Package, "Versão instalada", installedText, StateOf(item) is LibraryState.UpdateAvailable or LibraryState.VerificationRequired ? Yellow : Color.White, _iconSheet, new Rectangle(215, 535, 490, 440)), 2, 0); row.Controls.Add(FactCard(UiIcon.Calendar, "Instalada em", installed is null ? "—" : installed.InstalledAt.LocalDateTime.ToString("dd/MM/yyyy HH:mm"), Color.White, _iconSheet, new Rectangle(850, 525, 490, 440)), 3, 0); return row;
    }
    private Control FactCard(UiIcon icon, string caption, string value, Color accent, Image? image = null, Rectangle? sourceRectangle = null) { var frame = new TableLayoutPanel { Dock = DockStyle.Fill, Margin = new Padding(0, 0, 10, 0), BackColor = Border, ColumnCount = 3, RowCount = 2, Padding = new Padding(0) }; frame.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 2)); frame.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); frame.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 2)); frame.RowStyles.Add(new RowStyle(SizeType.Absolute, 2)); frame.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); var content = new Panel { Dock = DockStyle.Fill, BackColor = Panel, Margin = new Padding(0), Padding = new Padding(11, 7, 11, 5) }; frame.Controls.Add(content, 1, 1); var t = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 2, RowCount = 1, Margin = new Padding(0) }; t.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 58)); t.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); t.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); content.Controls.Add(t); var ico = new IconView(icon, accent, image, sourceRectangle) { Dock = DockStyle.Fill, Margin = new Padding(4) }; t.Controls.Add(ico, 0, 0); var text = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 1, RowCount = 2, Margin = new Padding(0) }; text.RowStyles.Add(new RowStyle(SizeType.Percent, 42)); text.RowStyles.Add(new RowStyle(SizeType.Percent, 58)); var captionLabel = LabelOf(caption, 8.5f, FontStyle.Regular, TextMuted); captionLabel.TextAlign = ContentAlignment.MiddleCenter; captionLabel.Dock = DockStyle.Fill; captionLabel.Margin = new Padding(0); text.Controls.Add(captionLabel, 0, 0); var val = LabelOf(value, 9, FontStyle.Regular, TextMain); val.AutoEllipsis = false; val.TextAlign = ContentAlignment.MiddleCenter; val.Dock = DockStyle.Fill; val.Margin = new Padding(0); text.Controls.Add(val, 0, 1); t.Controls.Add(text, 1, 0); return frame; }
    private static string WrapPath(string path) { if (path.Length <= 34) return path; var lines = new List<string>(); var remaining = path; while (remaining.Length > 34) { var cut = remaining.LastIndexOf('\\', Math.Min(33, remaining.Length - 1)); if (cut < 12) cut = 34; lines.Add(remaining[..cut].TrimEnd('\\')); remaining = remaining[(cut + 1)..]; } lines.Add(remaining); return string.Join(Environment.NewLine, lines); }
    private static void WireClicks(Control control, Action action) { control.Click += (_, _) => action(); foreach (Control child in control.Controls) WireClicks(child, action); }
    private static void SetToolTip(Control control, string text) { var tip = new ToolTip { AutoPopDelay = 10000, InitialDelay = 300, ReshowDelay = 100 }; tip.SetToolTip(control, text); foreach (Control child in control.Controls) SetToolTip(child, text); }
    private static void OpenSteamPage(Translation item) { if (!string.IsNullOrWhiteSpace(item.SteamAppId)) OpenUrl($"https://store.steampowered.com/app/{item.SteamAppId}/"); }
    private static bool IsValidGameFolder(Translation item, string? path)
    {
        if (string.IsNullOrWhiteSpace(path) || !Directory.Exists(path)) return false;
        if (item.ExecutableHints.Count == 0) return true;
        foreach (var hint in item.ExecutableHints.Where(x => !string.IsNullOrWhiteSpace(x)))
        {
            var normalized = hint.Replace('/', Path.DirectorySeparatorChar).TrimStart(Path.DirectorySeparatorChar);
            if (File.Exists(Path.Combine(path, normalized))) return true;
            try { if (Directory.EnumerateFiles(path, Path.GetFileName(normalized), SearchOption.AllDirectories).Any()) return true; } catch (UnauthorizedAccessException) { } catch (IOException) { }
        }
        return false;
    }
    private void LocateGameManually(Translation item)
    {
        using var picker = new FolderBrowserDialog { Description = $"Selecione a pasta de instalação de {item.Game}", UseDescriptionForTitle = true, ShowNewFolderButton = false, InitialDirectory = _storage.Config.GamePaths.GetValueOrDefault(item.Id) ?? Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86) };
        if (picker.ShowDialog(this) != DialogResult.OK) return;
        if (!IsValidGameFolder(item, picker.SelectedPath)) { var expected = item.ExecutableHints.Count == 0 ? "os arquivos do jogo" : string.Join(", ", item.ExecutableHints.Select(Path.GetFileName)); MessageBox.Show(this, $"Esta pasta não parece pertencer a {item.Game}.\r\n\r\nNão foi possível localizar: {expected}", "Pasta do jogo inválida", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; }
        _foundPaths[item.Id] = picker.SelectedPath; _storage.Config.GamePaths[item.Id] = picker.SelectedPath; _storage.SaveConfig(); EnsureStates(); RefreshGameList(); ShowDetails(item); Log($"Jogo localizado manualmente: {item.Game} — {picker.SelectedPath}");
    }
    private Control BuildActions(Translation item)
    {
        var state = StateOf(item); var located = state != LibraryState.NotFound; var installed = state is LibraryState.Installed or LibraryState.UpdateAvailable or LibraryState.VerificationRequired; const string missing = "O jogo precisa estar instalado ou localizado para usar esta função."; var row = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 4, Padding = new Padding(0, 4, 0, 4) }; for (var i = 0; i < 4; i++) row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25));
        var verify = ActionButton("Verificar tradução", Blue, installed, located ? "A tradução precisa estar instalada para ser verificada." : missing); verify.Click += async (_, _) => { if (installed) await VerifyAsync(item); else ShowBlockedAction(located ? "A tradução precisa estar instalada para ser verificada." : missing); }; row.Controls.Add(verify, 0, 0);
        var installText = state == LibraryState.UpdateAvailable ? "Atualizar tradução" : state == LibraryState.VerificationRequired ? "Verificar e reparar" : state == LibraryState.Installed ? "Tradução atualizada" : "Instalar tradução"; var canInstall = state is LibraryState.Available or LibraryState.UpdateAvailable or LibraryState.VerificationRequired; var installColor = state is LibraryState.UpdateAvailable or LibraryState.VerificationRequired ? Color.FromArgb(176, 122, 0) : Green; var installReason = !located ? missing : state == LibraryState.Installed ? "Esta tradução já está atualizada." : "A tradução não pode ser instalada neste estado."; var install = ActionButton(installText, installColor, canInstall || state == LibraryState.Installed, installReason); if (state == LibraryState.Installed) SetToolTip(install, "Esta tradução já está atualizada."); install.Click += async (_, _) => { if (canInstall) await InstallAsync(item); else ShowBlockedAction(installReason); }; row.Controls.Add(install, 1, 0);
        var remove = ActionButton("Desinstalar tradução", Color.FromArgb(150, 38, 48), installed, located ? "A tradução precisa estar instalada para ser desinstalada." : missing); remove.Click += async (_, _) => { if (installed) await RemoveAsync(item); else ShowBlockedAction(located ? "A tradução precisa estar instalada para ser desinstalada." : missing); }; row.Controls.Add(remove, 2, 0);
        var restore = ActionButton("Restaurar original", Color.FromArgb(38, 75, 119), located, missing); restore.Click += (_, _) => { if (!located) { ShowBlockedAction(missing); return; } if (string.IsNullOrWhiteSpace(item.SteamAppId)) { MessageBox.Show(this, "Este jogo não possui uma página Steam configurada.", "Steam", MessageBoxButtons.OK, MessageBoxIcon.Information); return; } RestoreSteam(item); }; row.Controls.Add(restore, 3, 0); return row;
    }
    private Button ActionButton(string text, Color color, bool available, string blockedReason) { var button = ButtonOf(text, false); button.BackColor = available ? color : Color.FromArgb(64, 72, 83); button.FlatAppearance.BorderColor = available ? ControlPaint.Light(color) : Color.FromArgb(101, 111, 124); button.ForeColor = available ? Color.White : Color.FromArgb(174, 181, 190); button.Cursor = available ? Cursors.Hand : Cursors.Help; if (!available) SetToolTip(button, blockedReason); return button; }
    private void ShowBlockedAction(string message) => MessageBox.Show(this, message, "Ação indisponível", MessageBoxButtons.OK, MessageBoxIcon.Information);
    private Control BuildInformation(Translation item)
    {
        var state = StateOf(item);
        var updateNotes = state == LibraryState.UpdateAvailable && item.Changelog.Count > 0 ? $"\r\n\r\nNOVA VERSÃO DISPONÍVEL — v{item.Version}\r\n{string.Join("\r\n", item.Changelog.Select(x => $"• {x}"))}" : "";
        var split = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Bg, ColumnCount = 2, Padding = new Padding(0, 7, 0, 7) }; split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 64)); split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 36)); var about = Card(); about.Margin = new Padding(0, 0, 10, 0); about.Padding = new Padding(18, 14, 18, 14); var text = new Label { Dock = DockStyle.Fill, BackColor = Panel, ForeColor = TextMuted, Font = Font, Text = $"SOBRE ESTA TRADUÇÃO\r\n\r\n{item.Description}{updateNotes}\r\n\r\nVersão {item.Version}\r\n• Pacote modular com instalação e backup automáticos\r\n• Verificação SHA-256 dos arquivos\r\n• Restauração segura dos arquivos originais", AutoEllipsis = true }; about.Controls.Add(text); var links = new FlowLayoutPanel { Dock = DockStyle.Bottom, Height = 38, BackColor = Panel }; links.Controls.Add(LinkOf("Ver no GitHub", item.ReleaseUrl)); var report = LinkOf("Reportar problema", ""); report.LinkClicked += (_, _) => ShowReportDialog(item); links.Controls.Add(report); about.Controls.Add(links); split.Controls.Add(about, 0, 0);
        var info = Card(); info.Padding = new Padding(18, 14, 18, 14); var table = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 2, RowCount = 6 }; table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 58)); table.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 42)); var heading = LabelOf("INFORMAÇÕES", 10, FontStyle.Bold, TextMain); table.Controls.Add(heading, 0, 0); table.SetColumnSpan(heading, 2); var packageSize = _storage.Installed.TryGetValue(item.Id, out var installed) ? installed.Files.Sum(x => x.InstalledSize) : 0; AddInfo(table, 1, "Arquivos traduzidos:", installed?.Files.Count.ToString() ?? "—"); AddInfo(table, 2, "Tamanho da tradução:", packageSize > 0 ? FormatBytes(packageSize) : "—"); AddInfo(table, 3, "Tipo de tradução:", "Instalação interna"); AddInfo(table, 4, "Backup:", "Ativado / OK"); AddInfo(table, 5, "Status:", StateText(StateOf(item))); info.Controls.Add(table); split.Controls.Add(info, 1, 0); return split;
    }
    private Control BuildSummary()
    {
        var card = Card(); card.Padding = new Padding(14, 10, 14, 10); var root = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 1, RowCount = 2 }; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 30)); root.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); root.Controls.Add(LabelOf("RESUMO DA BIBLIOTECA", 9, FontStyle.Bold, TextMain), 0, 0); var row = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel, ColumnCount = 5, Margin = new Padding(0) }; for (var i = 0; i < 5; i++) row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20)); row.Controls.Add(SummaryBox(UiIcon.Library, _summaryCatalog, "No catálogo", Color.FromArgb(185, 92, 255), StatusCrop(0)), 0, 0); row.Controls.Add(SummaryBox(UiIcon.CheckCircle, _summaryInstalled, "Instaladas", Green, StatusCrop(1)), 1, 0); row.Controls.Add(SummaryBox(UiIcon.Warning, _summaryUpdates, "Atualizações", Yellow, StatusCrop(2)), 2, 0); row.Controls.Add(SummaryBox(UiIcon.Download, _summaryAvailable, "Disponíveis", Color.FromArgb(58, 156, 255), StatusCrop(3)), 3, 0); row.Controls.Add(SummaryBox(UiIcon.MissingFolder, _summaryMissing, "Não instalados", Gray, StatusCrop(4)), 4, 0); root.Controls.Add(row, 0, 1); card.Controls.Add(root); UpdateSummary(); return card;
    }
    private Control SummaryBox(UiIcon icon, Label value, string caption, Color color, Rectangle crop) { var box = new Panel { Dock = DockStyle.Fill, BackColor = Panel2, Margin = new Padding(3), Padding = new Padding(8) }; var row = new TableLayoutPanel { Dock = DockStyle.Fill, BackColor = Panel2, ColumnCount = 3, RowCount = 1, Margin = new Padding(0) }; row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 48)); row.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 40)); row.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); row.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); var iconView = new IconView(icon, color, icon == UiIcon.MissingFolder ? null : _statusIconSheet, crop) { Dock = DockStyle.Fill, Margin = new Padding(3) }; row.Controls.Add(iconView, 0, 0); value.ForeColor = TextMain; value.Font = new Font(Font.FontFamily, 15, FontStyle.Bold); value.TextAlign = ContentAlignment.MiddleCenter; value.Dock = DockStyle.Fill; value.Margin = new Padding(0); row.Controls.Add(value, 1, 0); var captionLabel = LabelOf(caption, 8.3f, FontStyle.Regular, TextMuted); captionLabel.TextAlign = ContentAlignment.MiddleLeft; captionLabel.Dock = DockStyle.Fill; captionLabel.Margin = new Padding(0); row.Controls.Add(captionLabel, 2, 0); box.Controls.Add(row); return box; }
    private static Rectangle StatusCrop(int index) => index switch { 0 => new Rectangle(85, 105, 410, 400), 1 => new Rectangle(545, 105, 415, 400), 2 => new Rectangle(1010, 105, 425, 400), 3 => new Rectangle(235, 540, 480, 400), _ => new Rectangle(805, 535, 480, 410) };

    private async Task InstallAsync(Translation item)
    {
        var updating = StateOf(item) is LibraryState.UpdateAvailable or LibraryState.VerificationRequired; var action = updating ? "Atualizar" : "Instalar"; var path = _foundPaths.GetValueOrDefault(item.Id) ?? _storage.Config.GamePaths.GetValueOrDefault(item.Id); if (string.IsNullOrWhiteSpace(path) || !Directory.Exists(path)) { MessageBox.Show(this, "O jogo não foi localizado. Execute o escaneamento.", "Jogo não encontrado", MessageBoxButtons.OK, MessageBoxIcon.Warning); return; } if (!EnsureSteamRunning()) return; if (MessageBox.Show(this, $"{action} a tradução de {item.Game}?", $"Confirmar {action.ToLowerInvariant()}", MessageBoxButtons.YesNo, MessageBoxIcon.Question) != DialogResult.Yes) return; if (!EnsureGameClosed(item, path)) return;
        try { SetBusy(true, updating ? "Atualizando tradução" : "Instalando tradução"); await _translations.InstallAsync(item, path, new Progress<ProgressInfo>(UpdateOperation), _closing.Token); MessageBox.Show(this, updating ? "Tradução atualizada com sucesso." : "Tradução instalada com sucesso.", "BR Patch Hub", MessageBoxButtons.OK, MessageBoxIcon.Information); } catch (Exception ex) { Log(ex.Message); MessageBox.Show(this, ex.Message, updating ? "Falha na atualização" : "Falha na instalação", MessageBoxButtons.OK, MessageBoxIcon.Error); } finally { SetBusy(false); EnsureStates(); RefreshGameList(); ShowDetails(item); }
    }
    private async Task RemoveAsync(Translation item)
    {
        if (!EnsureSteamRunning()) return; if (MessageBox.Show(this, "Desinstalar a tradução e restaurar o backup original?", "Confirmar remoção", MessageBoxButtons.YesNo, MessageBoxIcon.Question) != DialogResult.Yes) return; var gamePath = _storage.Installed.GetValueOrDefault(item.Id)?.GamePath ?? _storage.Config.GamePaths.GetValueOrDefault(item.Id); if (!EnsureGameClosed(item, gamePath)) return; try { SetBusy(true, "Removendo tradução"); var result = await _translations.RemoveAsync(item, new Progress<ProgressInfo>(UpdateOperation), _closing.Token); var note = result.RequiresSteamRestore ? " Alguns arquivos precisarão da verificação da Steam." : ""; MessageBox.Show(this, "Tradução removida com sucesso." + note, "BR Patch Hub", MessageBoxButtons.OK, MessageBoxIcon.Information); } catch (Exception ex) { Log(ex.Message); MessageBox.Show(this, ex.Message, "Falha na remoção", MessageBoxButtons.OK, MessageBoxIcon.Error); } finally { SetBusy(false); EnsureStates(); RefreshGameList(); ShowDetails(item); }
    }
    private async Task VerifyAsync(Translation item)
    {
        if (!_storage.Installed.TryGetValue(item.Id, out var installed)) { MessageBox.Show(this, "Esta tradução ainda não está instalada.", "Verificação", MessageBoxButtons.OK, MessageBoxIcon.Information); return; } SetBusy(true, "Verificando arquivos"); var problems = 0; IProgress<ProgressInfo> progress = new Progress<ProgressInfo>(UpdateOperation); try { await Task.Run(async () => { for (var i = 0; i < installed.Files.Count; i++) { var file = installed.Files[i]; var path = Path.Combine(installed.GamePath, file.RelativePath); if (!File.Exists(path) || !string.Equals(await FileTools.Sha256Async(path), file.InstalledHash, StringComparison.OrdinalIgnoreCase)) problems++; progress.Report(new ProgressInfo($"Verificando arquivo {i + 1} de {installed.Files.Count}", (i + 1) * 100 / Math.Max(1, installed.Files.Count))); } }); } finally { SetBusy(false); } MessageBox.Show(this, problems == 0 ? "Todos os arquivos estão corretos." : $"Foram encontrados {problems} arquivo(s) alterado(s) ou ausente(s).", "Verificação concluída", MessageBoxButtons.OK, problems == 0 ? MessageBoxIcon.Information : MessageBoxIcon.Warning);
    }
    private void RestoreSteam(Translation item) { if (!EnsureSteamRunning()) return; if (MessageBox.Show(this, "A Steam verificará e restaurará os arquivos originais. Continuar?", "Restaurar jogo original", MessageBoxButtons.YesNo, MessageBoxIcon.Warning) != DialogResult.Yes) return; var path = _foundPaths.GetValueOrDefault(item.Id) ?? _storage.Config.GamePaths.GetValueOrDefault(item.Id); if (!EnsureGameClosed(item, path)) return; try { SteamService.Validate(item.SteamAppId); } catch (Exception ex) { MessageBox.Show(this, ex.Message, "Steam", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
    private bool EnsureSteamRunning()
    {
        if (SteamService.IsRunning()) return true;
        using var dialog = new Form { Text = "Steam fechada", StartPosition = FormStartPosition.CenterParent, ClientSize = new Size(470, 190), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.FixedDialog, MaximizeBox = false, MinimizeBox = false, ShowInTaskbar = false };
        var text = new Label { Dock = DockStyle.Top, Height = 112, Padding = new Padding(22, 20, 22, 8), ForeColor = TextMain, BackColor = Panel, Font = new Font("Segoe UI", 10), Text = "A Steam precisa estar aberta antes de instalar, atualizar, remover ou restaurar uma tradução.\r\n\r\nAbra a Steam e tente novamente." };
        var buttons = new FlowLayoutPanel { Dock = DockStyle.Bottom, Height = 62, FlowDirection = FlowDirection.RightToLeft, Padding = new Padding(12, 8, 18, 10), BackColor = Panel };
        var cancel = ButtonOf("Cancelar", false); cancel.Size = new Size(120, 38); cancel.Dock = DockStyle.None; cancel.DialogResult = DialogResult.Cancel;
        var open = ButtonOf("Abrir Steam", true); open.Size = new Size(130, 38); open.Dock = DockStyle.None; open.DialogResult = DialogResult.OK;
        buttons.Controls.Add(cancel); buttons.Controls.Add(open); dialog.Controls.Add(text); dialog.Controls.Add(buttons); dialog.AcceptButton = open; dialog.CancelButton = cancel;
        if (dialog.ShowDialog(this) == DialogResult.OK) { try { SteamService.Start(); } catch (Exception ex) { MessageBox.Show(this, ex.Message, "Steam", MessageBoxButtons.OK, MessageBoxIcon.Error); } }
        return false;
    }
    private bool EnsureGameClosed(Translation item, string? gamePath)
    {
        while (true)
        {
            var running = GameProcessService.FindRunning(item, gamePath);
            if (running is null) return true;
            using var dialog = new Form { Text = "Jogo em execução", StartPosition = FormStartPosition.CenterParent, ClientSize = new Size(510, 218), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.FixedDialog, MaximizeBox = false, MinimizeBox = false, ShowInTaskbar = false };
            var text = new Label { Dock = DockStyle.Fill, Padding = new Padding(22, 20, 22, 8), ForeColor = TextMain, BackColor = Panel, Font = new Font("Segoe UI", 10), Text = $"Feche o jogo para continuar.\r\n\r\nProcesso encontrado: {running}\r\n\r\nO BR Patch Hub nunca fechará o jogo à força." };
            var buttons = new FlowLayoutPanel { Dock = DockStyle.Bottom, Height = 62, FlowDirection = FlowDirection.RightToLeft, Padding = new Padding(12, 8, 18, 10), BackColor = Panel };
            var cancel = ButtonOf("Cancelar", false); cancel.Size = new Size(120, 38); cancel.Dock = DockStyle.None; cancel.DialogResult = DialogResult.Cancel;
            var retry = ButtonOf("Verificar novamente", true); retry.Size = new Size(170, 38); retry.Dock = DockStyle.None; retry.DialogResult = DialogResult.Retry;
            buttons.Controls.Add(cancel); buttons.Controls.Add(retry); dialog.Controls.Add(text); dialog.Controls.Add(buttons); dialog.AcceptButton = retry; dialog.CancelButton = cancel;
            if (dialog.ShowDialog(this) != DialogResult.Retry) return false;
        }
    }
    private async Task ShowInstallQueueAsync()
    {
        if (_busy) return;
        EnsureStates();
        var choices = _catalog.Translations.Where(x => StateOf(x) is LibraryState.Available or LibraryState.UpdateAvailable).Select(x => new QueueChoice(x, _foundPaths.GetValueOrDefault(x.Id) ?? _storage.Config.GamePaths.GetValueOrDefault(x.Id) ?? "")).Where(x => Directory.Exists(x.Path)).ToList();
        if (choices.Count == 0) { MessageBox.Show(this, "Não há traduções disponíveis para instalar ou atualizar nos jogos encontrados.", "Fila de instalações", MessageBoxButtons.OK, MessageBoxIcon.Information); return; }
        using var select = new Form { Text = "Fila de instalações", StartPosition = FormStartPosition.CenterParent, ClientSize = new Size(590, 430), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.FixedDialog, MaximizeBox = false, MinimizeBox = false, ShowInTaskbar = false };
        var instruction = new Label { Dock = DockStyle.Top, Height = 58, Padding = new Padding(16, 15, 16, 4), Text = "Marque as traduções que deseja instalar ou atualizar:", ForeColor = TextMain, BackColor = Panel };
        var list = new CheckedListBox { Dock = DockStyle.Fill, BackColor = Bg, ForeColor = TextMain, BorderStyle = BorderStyle.FixedSingle, CheckOnClick = true, Font = new Font("Segoe UI", 10), IntegralHeight = false };
        foreach (var choice in choices) list.Items.Add(choice, true);
        var buttons = new FlowLayoutPanel { Dock = DockStyle.Bottom, Height = 62, FlowDirection = FlowDirection.RightToLeft, Padding = new Padding(12, 8, 18, 10), BackColor = Panel };
        var cancel = ButtonOf("Cancelar", false); cancel.Size = new Size(120, 38); cancel.Dock = DockStyle.None; cancel.DialogResult = DialogResult.Cancel;
        var start = ButtonOf("Iniciar fila", true); start.Size = new Size(140, 38); start.Dock = DockStyle.None; start.DialogResult = DialogResult.OK;
        buttons.Controls.Add(cancel); buttons.Controls.Add(start); select.Controls.Add(list); select.Controls.Add(instruction); select.Controls.Add(buttons); select.AcceptButton = start; select.CancelButton = cancel;
        if (select.ShowDialog(this) != DialogResult.OK) return;
        var selected = list.CheckedItems.Cast<QueueChoice>().ToList(); if (selected.Count == 0) return; if (!EnsureSteamRunning()) return;

        using var progressForm = new Form { Text = "Fila de instalações", StartPosition = FormStartPosition.CenterParent, ClientSize = new Size(650, 390), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.FixedDialog, MaximizeBox = false, MinimizeBox = false, ShowInTaskbar = false, ControlBox = false };
        var status = new Label { Dock = DockStyle.Top, Height = 66, Padding = new Padding(18, 14, 18, 5), ForeColor = TextMain, BackColor = Panel, Text = "Preparando fila..." };
        var overall = new ProgressBar { Dock = DockStyle.Top, Height = 24, Minimum = 0, Maximum = 100, Style = ProgressBarStyle.Continuous, Margin = new Padding(18) };
        var results = new ListBox { Dock = DockStyle.Fill, BackColor = Bg, ForeColor = TextMain, BorderStyle = BorderStyle.FixedSingle, Font = new Font("Segoe UI", 9.5f) };
        var stop = false; var stopButton = ButtonOf("Cancelar pendentes", false); stopButton.Dock = DockStyle.Bottom; stopButton.Height = 48; stopButton.Click += (_, _) => { stop = true; stopButton.Enabled = false; stopButton.Text = "A fila será interrompida após o item atual"; };
        progressForm.Controls.Add(results); progressForm.Controls.Add(overall); progressForm.Controls.Add(status); progressForm.Controls.Add(stopButton); progressForm.Show(this); progressForm.Refresh();
        var ok = 0; var failed = 0; var skipped = 0; _busy = true;
        try
        {
            for (var index = 0; index < selected.Count; index++)
            {
                if (stop) { skipped += selected.Count - index; break; }
                var choice = selected[index]; status.Text = $"Item {index + 1} de {selected.Count}: {choice.Translation.Game}"; results.Items.Add($"Aguardando: {choice.Translation.Game}");
                if (!EnsureGameClosed(choice.Translation, choice.Path)) { results.Items[results.Items.Count - 1] = $"Ignorada: {choice.Translation.Game} (jogo aberto)"; skipped++; continue; }
                try
                {
                    var itemProgress = new Progress<ProgressInfo>(info => { status.Text = $"Item {index + 1} de {selected.Count}: {info.Message}"; var part = info.Percent ?? 0; overall.Value = Math.Clamp((index * 100 + part) / selected.Count, 0, 100); });
                    await _translations.InstallAsync(choice.Translation, choice.Path, itemProgress, _closing.Token); ok++; results.Items[results.Items.Count - 1] = $"Concluída: {choice.Translation.Game}";
                }
                catch (Exception ex) { failed++; Log($"Fila - {choice.Translation.Game}: {ex.Message}"); results.Items[results.Items.Count - 1] = $"Falhou: {choice.Translation.Game} — {ex.Message}"; }
                overall.Value = Math.Clamp((index + 1) * 100 / selected.Count, 0, 100); results.TopIndex = Math.Max(0, results.Items.Count - 1); Application.DoEvents();
            }
        }
        finally { _busy = false; progressForm.Close(); EnsureStates(); RefreshGameList(); if (_selected is not null) ShowDetails(_selected); }
        MessageBox.Show(this, $"Fila concluída.\r\n\r\nConcluídas: {ok}\r\nFalhas: {failed}\r\nPendentes canceladas/ignoradas: {skipped}", "Fila de instalações", MessageBoxButtons.OK, failed == 0 ? MessageBoxIcon.Information : MessageBoxIcon.Warning);
    }
    private void ShowReportDialog(Translation item)
    {
        var state = StateText(StateOf(item)); var logLines = _log.Lines.Where(x => !string.IsNullOrWhiteSpace(x)).TakeLast(35);
        var body = $"Descrição do problema:\r\n[Conte aqui o que aconteceu]\r\n\r\n--- Diagnóstico do BR Patch Hub ---\r\nBR Patch Hub: v{AppConstants.AppVersion}\r\nWindows: {Environment.OSVersion}\r\nJogo: {item.Game}\r\nTradução: v{item.Version}\r\nEstado: {state}\r\nSteam AppID: {item.SteamAppId}\r\nData: {DateTimeOffset.Now:yyyy-MM-dd HH:mm:ss zzz}\r\n\r\nLog recente:\r\n{string.Join("\r\n", logLines)}";
        body = SanitizeReport(body, item);
        using var dialog = new Form { Text = "Prévia do relatório", StartPosition = FormStartPosition.CenterParent, ClientSize = new Size(760, 610), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.Sizable, MinimizeBox = false, ShowInTaskbar = false };
        var notice = new Label { Dock = DockStyle.Top, Height = 70, Padding = new Padding(16, 12, 16, 5), ForeColor = TextMain, BackColor = Panel, Text = "Revise o relatório antes de continuar. Caminhos pessoais foram ocultados. Nada será enviado automaticamente; o GitHub abrirá a página para sua confirmação final." };
        var preview = new TextBox { Dock = DockStyle.Fill, Multiline = true, ScrollBars = ScrollBars.Both, WordWrap = false, BackColor = Bg, ForeColor = TextMain, BorderStyle = BorderStyle.FixedSingle, Font = new Font("Consolas", 9.5f), Text = body };
        var buttons = new FlowLayoutPanel { Dock = DockStyle.Bottom, Height = 62, FlowDirection = FlowDirection.RightToLeft, Padding = new Padding(12, 8, 18, 10), BackColor = Panel };
        var cancel = ButtonOf("Cancelar", false); cancel.Size = new Size(110, 38); cancel.Dock = DockStyle.None; cancel.DialogResult = DialogResult.Cancel;
        var open = ButtonOf("Abrir issue no GitHub", true); open.Size = new Size(180, 38); open.Dock = DockStyle.None; open.DialogResult = DialogResult.OK;
        var copy = ButtonOf("Copiar relatório", false); copy.Size = new Size(145, 38); copy.Dock = DockStyle.None; copy.Click += (_, _) => { Clipboard.SetText(preview.Text); MessageBox.Show(dialog, "Relatório copiado.", "BR Patch Hub", MessageBoxButtons.OK, MessageBoxIcon.Information); };
        buttons.Controls.Add(cancel); buttons.Controls.Add(open); buttons.Controls.Add(copy); dialog.Controls.Add(preview); dialog.Controls.Add(notice); dialog.Controls.Add(buttons); dialog.AcceptButton = open; dialog.CancelButton = cancel;
        if (dialog.ShowDialog(this) == DialogResult.OK) { var title = Uri.EscapeDataString($"[BR Patch Hub] Problema com {item.Game}"); var reportBody = Uri.EscapeDataString(SanitizeReport(preview.Text, item)); OpenUrl($"{IssueUrl(item)}?title={title}&body={reportBody}"); }
    }
    private string SanitizeReport(string text, Translation item)
    {
        var values = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase) { ["%USERPROFILE%"] = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), ["%CENTRAL_DATA%"] = _storage.Root, ["%GAME_FOLDER%"] = _storage.Installed.GetValueOrDefault(item.Id)?.GamePath ?? _foundPaths.GetValueOrDefault(item.Id) ?? _storage.Config.GamePaths.GetValueOrDefault(item.Id) };
        foreach (var pair in values.Where(x => !string.IsNullOrWhiteSpace(x.Value)).OrderByDescending(x => x.Value!.Length)) text = text.Replace(pair.Value!, pair.Key, StringComparison.OrdinalIgnoreCase);
        return text.Length > 6000 ? text[..6000] + "\r\n[log reduzido]" : text;
    }
    private void ShowSettings()
    {
        using var dialog = new Form { Text = "Configurações — BR Patch Hub", StartPosition = FormStartPosition.CenterParent, Size = new Size(470, 330), BackColor = Panel, ForeColor = TextMain, Font = Font, FormBorderStyle = FormBorderStyle.FixedDialog, MaximizeBox = false, MinimizeBox = false }; var layout = new FlowLayoutPanel { Dock = DockStyle.Fill, FlowDirection = FlowDirection.TopDown, Padding = new Padding(24), BackColor = Panel, WrapContents = false }; layout.Controls.Add(LabelOf("CONFIGURAÇÕES", 14, FontStyle.Bold, TextMain, 390)); foreach (var text in new[] { "Escanear a Steam automaticamente ao iniciar", "Verificar catálogo ao iniciar", "Confirmar antes de instalar ou remover", "Mostrar log técnico quando houver erro" }) layout.Controls.Add(new CheckBox { Text = text, Checked = true, AutoSize = true, ForeColor = TextMain, Margin = new Padding(0, 12, 0, 0) }); var open = ButtonOf("Abrir pasta do BR Patch Hub", false); open.Width = 390; open.Height = 42; open.Margin = new Padding(0, 18, 0, 0); open.Click += (_, _) => OpenFolder(_storage.Root); layout.Controls.Add(open); dialog.Controls.Add(layout); dialog.ShowDialog(this);
    }
    private void ToggleLog() { if (_logToggle.Tag is not TableLayoutPanel outer) return; var visible = outer.RowStyles[1].Height > 0; outer.RowStyles[1].SizeType = SizeType.Absolute; outer.RowStyles[1].Height = visible ? 0 : 160; _logToggle.Text = visible ? "Ver log" : "Ocultar log"; }
    private void UpdateSummary() { if (_summaryCatalog.IsDisposed) return; var installed = _states.Values.Count(x => x is LibraryState.Installed or LibraryState.UpdateAvailable or LibraryState.VerificationRequired); var updates = _states.Values.Count(x => x == LibraryState.UpdateAvailable); var available = _states.Values.Count(x => x == LibraryState.Available); var missing = _states.Values.Count(x => x == LibraryState.NotFound); _summaryCatalog.Text = _catalog.Translations.Count.ToString(); _summaryInstalled.Text = installed.ToString(); _summaryUpdates.Text = updates.ToString(); _summaryAvailable.Text = available.ToString(); _summaryMissing.Text = missing.ToString(); _legendInstalled.Text = installed.ToString(); _legendUpdates.Text = updates.ToString(); _legendAvailable.Text = available.ToString(); _legendMissing.Text = missing.ToString(); }
    private LibraryState StateOf(Translation item) => _states.GetValueOrDefault(item.Id, LibraryState.NotFound);
    private static bool FilterMatches(LibraryState s, string f) => f switch { "Instalados" => s is LibraryState.Installed or LibraryState.UpdateAvailable or LibraryState.VerificationRequired, "Disponíveis" => s == LibraryState.Available, "Atualizações" => s == LibraryState.UpdateAvailable, "Não instalados" => s == LibraryState.NotFound, _ => true };
    private static string StateText(LibraryState s) => s switch { LibraryState.Installed => "Atualizada", LibraryState.Available => "Tradução não instalada", LibraryState.UpdateAvailable => "Atualização disponível", LibraryState.VerificationRequired => "Verificação necessária", _ => "Não instalado" };
    private static Color StateColor(LibraryState s) => s switch { LibraryState.Installed => Green, LibraryState.Available => Color.FromArgb(58, 156, 255), LibraryState.UpdateAvailable => Yellow, LibraryState.VerificationRequired => Color.FromArgb(255, 153, 51), _ => Gray };
    private static string CompatibilityText(Translation item, LibraryState state) => state switch { LibraryState.NotFound => "O jogo não foi encontrado. Se estiver instalado, localize a pasta manualmente.", LibraryState.Available => "Jogo localizado. Tradução pronta para instalar.", LibraryState.UpdateAvailable => "Uma nova versão está pronta para instalar.", LibraryState.VerificationRequired => "A versão instalada precisa ser verificada.", _ => string.IsNullOrWhiteSpace(item.SteamAppId) ? "Compatibilidade não verificada" : "Pronta para a versão Steam detectada" };
    private static string FormatBytes(long b) => b >= 1024 * 1024 ? $"{b / 1024d / 1024d:0.0} MB" : $"{b / 1024d:0.0} KB";
    private static string IssueUrl(Translation item) { if (Uri.TryCreate(item.ReleaseUrl, UriKind.Absolute, out var uri) && uri.Host.Equals("github.com", StringComparison.OrdinalIgnoreCase)) { var p = uri.AbsolutePath.Trim('/').Split('/'); if (p.Length >= 2) return $"https://github.com/{p[0]}/{p[1]}/issues/new"; } return AppConstants.OfficialRepositoryUrl + "/issues/new"; }
    private void SetBusy(bool busy, string? title = null) { _busy = busy; UseWaitCursor = busy; if (_operationPanel is not null && _detailRoot is not null) { _operationPanel.Visible = busy; _detailRoot.RowStyles[3].Height = busy ? 78 : 0; _detailRoot.PerformLayout(); } if (busy) { if (_operationTitle is not null && !string.IsNullOrWhiteSpace(title)) _operationTitle.Text = title; if (_operationDetail is not null) _operationDetail.Text = "Preparando..."; if (_operationPercent is not null) _operationPercent.Text = "0%"; if (_operationBar is not null) { _operationBar.Style = ProgressBarStyle.Marquee; _operationBar.MarqueeAnimationSpeed = 25; } } }
    private void UpdateOperation(ProgressInfo info) { if (InvokeRequired) { BeginInvoke(() => UpdateOperation(info)); return; } if (_operationDetail is not null) _operationDetail.Text = info.Message; _generalStatus.Text = info.Message; if (!info.Percent.HasValue) { if (_operationBar is not null) { _operationBar.Style = ProgressBarStyle.Marquee; _operationBar.MarqueeAnimationSpeed = 25; } if (_operationPercent is not null) _operationPercent.Text = "..."; return; } var percent = Math.Clamp(info.Percent.Value, 0, 100); if (_operationBar is not null) { _operationBar.Style = ProgressBarStyle.Continuous; _operationBar.Value = percent; } if (_operationPercent is not null) _operationPercent.Text = $"{percent}%"; }
    private void Log(string message) { if (InvokeRequired) { BeginInvoke(() => Log(message)); return; } _log.AppendText($"[{DateTime.Now:HH:mm:ss}] {message}\r\n"); _log.ScrollToCaret(); }
    private static void OpenUrl(string? url) { if (!string.IsNullOrWhiteSpace(url)) Process.Start(new ProcessStartInfo(url) { UseShellExecute = true }); }
    private static void OpenFolder(string? path) { if (!string.IsNullOrWhiteSpace(path) && Directory.Exists(path)) Process.Start(new ProcessStartInfo("explorer.exe", $"\"{path}\"") { UseShellExecute = true }); }
    private static Panel Card() { var p = new Panel { Dock = DockStyle.Fill, BackColor = Panel }; p.Paint += (_, e) => { using var pen = new Pen(Border); e.Graphics.DrawRectangle(pen, 0, 0, Math.Max(0, p.ClientSize.Width - 2), Math.Max(0, p.ClientSize.Height - 2)); }; return p; }
    private static Label LabelOf(string text, float size, FontStyle style, Color color, int width = 0) => new() { Text = text, Dock = width == 0 ? DockStyle.Fill : DockStyle.None, Width = width, Height = 26, ForeColor = color, BackColor = Color.Transparent, Font = new Font("Segoe UI", size, style), TextAlign = ContentAlignment.MiddleLeft, AutoEllipsis = true };
    private static Button ButtonOf(string text, bool primary) { var b = new Button { Text = text, Dock = DockStyle.Fill, Margin = new Padding(4), FlatStyle = FlatStyle.Flat, BackColor = primary ? Blue : Panel2, ForeColor = TextMain, Font = new Font("Segoe UI", 10), Cursor = Cursors.Hand, UseVisualStyleBackColor = false, TextAlign = ContentAlignment.MiddleCenter }; b.FlatAppearance.BorderSize = 1; b.FlatAppearance.BorderColor = primary ? Blue : Border; return b; }
    private static void StyleInput(Control input) { var inputColor = Color.FromArgb(30, 67, 105); input.BackColor = inputColor; input.ForeColor = TextMain; input.Font = new Font("Segoe UI", 10); if (input is TextBox textBox) { textBox.BorderStyle = BorderStyle.FixedSingle; textBox.Padding = new Padding(8, 3, 8, 3); } if (input is ComboBox comboBox) { comboBox.FlatStyle = FlatStyle.Flat; comboBox.DrawMode = DrawMode.OwnerDrawFixed; comboBox.DrawItem += (_, e) => { if (e.Index < 0) return; using var background = new SolidBrush(inputColor); e.Graphics.FillRectangle(background, e.Bounds); using var brush = new SolidBrush(TextMain); e.Graphics.DrawString(comboBox.Items[e.Index]?.ToString() ?? "", comboBox.Font, brush, e.Bounds.Left + 6, e.Bounds.Top + 2); }; } }
    private static LinkLabel LinkOf(string text, string url) { var l = new LinkLabel { Text = text, AutoSize = true, LinkColor = Color.FromArgb(58, 156, 255), ActiveLinkColor = Color.White, BackColor = Panel, Margin = new Padding(0, 9, 28, 0) }; l.LinkClicked += (_, _) => OpenUrl(url); return l; }
    private static void AddInfo(TableLayoutPanel table, int row, string name, string value) { table.RowStyles.Add(new RowStyle(SizeType.Percent, 16)); table.Controls.Add(LabelOf(name, 9, FontStyle.Regular, TextMuted), 0, row); var label = LabelOf(value, 9, FontStyle.Regular, value.Contains("OK") ? Green : TextMain); label.TextAlign = ContentAlignment.MiddleRight; table.Controls.Add(label, 1, row); }
}
